dataset: torch/cifar10
num_classes: 10
img_size: 32
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
# aa: rand-m9-mstd0.5-inc1
mixup: 0.0
mixup_off_epoch: 175
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0
reprob: 0.25
remode: pixel
amp: True
model: cifar10_resnet18
model_ema: False
batch_size: 128
lr: 55e-5
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 300
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.00001
opt: adamw
smoothing: 0.0
workers: 1
wq_enable: True
wq_mode: "LSQ"
wq_bitw: 2
aq_enable: True
aq_mode: "LSQ"
aq_bitw: 2
qmodules: 
  - "layer1.0.conv1"
  - "layer1.0.conv2"
  - "layer1.1.conv1"
  - "layer1.1.conv2"
  - "layer2.0.conv1"
  - "layer2.0.conv2"
  - "layer2.0.downsample.0"
  - "layer2.1.conv1"
  - "layer2.1.conv2"
  - "layer3.0.conv1"
  - "layer3.0.conv2"
  - "layer3.0.downsample.0"
  - "layer3.1.conv1"
  - "layer3.1.conv2"
  - "layer4.0.conv1"
  - "layer4.0.conv2"
  - "layer4.0.downsample.0"
  - "layer4.1.conv1"
  - "layer4.1.conv2"
